-- 000001_init_schema.up.example.sql
-- Creates "examples" table matching the Go GORM struct ExampleEntity (PostgreSQL)

CREATE TABLE IF NOT EXISTS examples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    count INTEGER NOT NULL
);

-- -- Trigger function to keep updated_at current on UPDATE
-- CREATE OR REPLACE FUNCTION examples_updated_at_trigger()
-- RETURNS TRIGGER AS $$
-- BEGIN
--     NEW.updated_at = now();
--     RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- -- Attach trigger to table
-- DROP TRIGGER IF EXISTS set_updated_at ON examples;
-- CREATE TRIGGER set_updated_at
-- BEFORE UPDATE ON examples
-- FOR EACH ROW
-- EXECUTE FUNCTION examples_updated_at_trigger();